bot_token = ""    # discord bot token
rust_error_ch = "dest2"    # `destination` that any rust errors get sent to

# these are the destinations that msgs can be sent to,
# for each destination you need to get the id from discord and say if it is
# a server chanel or a DM
[destinations]
dest1 = {id = 123456789123456789, ch_type="dm"}
dest2 = {id = 999999999999999999, ch_type="server"}


[vaults.VAULTNAME1]              # replace VAULTNAME1 with the name of your vault
destination = "dest1"           # name of destination for this vaults notifications
debug_destination = "dest1"     # this is only used for debugging, just leave it the same as `destination` if you dont need it
root_dir = "/path/to/vault1"     # path of your obsidian vault
todo_path = "General/TODO.md"
todo_section_header = "TODO"

# you can have multiple vaults
[vaults.VAULTNAME2]
destination = "dest2"
debug_destination = "dest2"
root_dir = "/path/to/vault2"
